import "./globals.css";
import { Figtree } from "next/font/google";

const figtree = Figtree({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata = {
  title: "Alberto || Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${figtree.className} mx-auto w-[90%] md:w-[80%] 
      my-12 md:my-16 lg:my-24`}>
        {children}
      </body>
    </html>
  );
}
