import Header from "./components/Header"
import ThemeContextProvider from "./context/ThemeContext"
import "./globals.css"
import { Sofia_Sans_Condensed } from "next/font/google"

const sofia = Sofia_Sans_Condensed({
  subsets: ["latin"],
  weight: ["700"],
})

export const metadata = {
  title: "Alberto || Portfolio",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ThemeContextProvider>
        <body className={`${sofia.className} bg-slate-200 dark:bg-slate-800 
        dark:text-slate-200 text-black`}>
          <Header />
          {children}
        </body>
      </ThemeContextProvider>
    </html>
  )
}
